price = int(input("enter the price of an item:"))
quantity = int(input("enter the quantity of an item 1:"))
price2 = int(input("enter the price of item 2:"))
quantity2 = int(input("enter the quantity of item 2:"))
price3 = int(input("enter the price of item 3:"))
quantity3 = int(input("enter the quantity of item 3:"))